#cloud-config
runcmd:
- mkdir /run/yc
- "curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh > /run/yc/install.sh"
- [ sudo, bash, /run/yc/install.sh]
- [ sudo, mkdir, /data ]
- |
  sudo /root/yandex-cloud/bin/yc lockbox payload get \
    --id "{{ env.YC_SECRET_ID }}" \
    --key config \
    --cloud-id "{{ env.YC_CLOUD_ID }}" \
    --folder-id "{{ env.YC_FOLDER_ID }}" > /data/.env

users:
  - name: {{ env.YC_VM_USERNAME }}
    groups: sudo
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    ssh-authorized-keys:
      - {{ env.SSH_KEY }}
