#cloud-config
users:
  - name: {{ env.YC_VM_USERNAME }}
    groups: sudo
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    ssh-authorized-keys:
      - {{ env.SSH_KEY }}
      # - {{ env.cat ~/.ssh/id_rsa.pub }}

write_files:
  - path: /etc/profile.d/custom-env.sh
    content: |
      echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
      echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
      echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
      echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
      echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
      echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
      echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
      echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      echo "CLIENT_YANDEX_ID=${{ secrets.CLIENT_YANDEX_ID }}" >> .env
      echo "CLIENT_YANDEX_SECRET=${{ secrets.CLIENT_YANDEX_SECRET }}" >> .env
      echo "MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}" >> .env
      echo "MINIO_PORT=${{ secrets.MINIO_PORT }}" >> .env
      echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> .env
      echo "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> .env

runcmd:
  - chmod +x /etc/profile.d/custom-env.sh
